---
- name: set default foward policy for ufw
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'
  notify:
    - restart ufw
- name: template NAT configuration through ufw
  template: src=roles/gateway/templates/before.rules.j2 dest=/etc/ufw/before.rules owner=root group=root mode=644 backup=yes
  notify:
    - restart ufw
- name: set sysctl to allow ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: yes
