---
- hosts: allinone
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - include: roles/common/tasks/base.yml
    - include: roles/common/tasks/network-interfaces.yml
    - include: roles/common/tasks/dhcp-interface.yml interface={{ wan_interface }}
    - include: roles/common/tasks/static-interface.yml interface={{ lan_interface }} address={{ lan_address }} netmask={{ lan_netmask }}
    - include: roles/common/tasks/ufw.yml
    - include: roles/common/tasks/ufw_rule.yml rule=allow src={{ lan_network }} dest={{ lan_network }}
    - include: roles/common/tasks/ufw_rule.yml rule=deny src={{ lan_network }} dest="192.168.0.0/16"
    - include: roles/common/tasks/ufw_rule.yml rule=deny src={{ lan_network }} dest="10.0.0.0/8"
    - include: roles/common/tasks/ufw_rule.yml rule=deny src={{ lan_network }} dest="172.16.0.0/12"
    - include: roles/common/tasks/ufw_rule.yml rule=allow src={{ lan_network }}
    - include: roles/ap/tasks/main.yml
    - include: roles/dnsdhcp/tasks/main.yml
    - include: roles/gateway/tasks/main.yml
  handlers:
    - include: roles/common/handlers/main.yml
    - include: roles/ap/handlers/main.yml
    - include: roles/dnsdhcp/handlers/main.yml
